name = "JuliaGram"
uuid = "a2a86584-f9f0-4d81-853e-84db2b0bb473"
authors = ["Matteo Mazzanti"]
version = "1.0.0-DEV"

[compat]
julia = "1.10.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
